"use client";

import { useEffect, useMemo, useState } from "react";
import ASHAssistant from "./ASHAssistant";
import CursorNetwork from "./CursorNetwork";
import MechanicalElements from "./MechanicalElements";

type Project = {
  title: string;
  category: string;
  tags: string[];
  description: string;
  metric: string;
  hero?: string;
  gallery?: { src: string; caption: string }[];
  sections?: { title: string; body: string }[];
  highlights?: string[];
};

const projects: Project[] = [
  { title: "Improved Rapid Change Wheel Design", category: "Maintenance", tags: ["SolidWorks", "Reliability", "Design", "Serviceability"], description: "Reworked a hoist caster assembly so wheel replacement can be completed at the installation point without removing the heavy assembly or performing hot work.", metric: "Maintenance", sections: [{ title: "The problem", body: "The original caster was installed at height. Wheel replacement required removing the heavy subassembly, taking it to a maintenance shop, grinding off a welded axle end, replacing the wheel, welding the axle again, and reinstalling the assembly." }, { title: "Design approach", body: "The redesign uses a new caster housing with a removable axle secured by a cotter pin. The housing remains installed on the hoist while only the wheel and axle are removed for replacement." }, { title: "Result", body: "The maintenance procedure becomes a simple remove-pin, slide-axle, replace-wheel, reinstall-axle sequence. This removes the need for welding and grinding during routine wheel replacement and reduces handling and downtime." }], highlights: ["Removable axle", "Cotter-pin retention", "No routine welding", "At-height serviceability", "Lower maintenance effort"] },
  { title: "Industrial Electroplating Barrel Improvements", category: "Design", tags: ["CAD", "Manufacturing", "Reliability"], description: "Improved access to difficult mid-assembly connections and addressed rotation-related wear in an industrial electrocoating setup.", metric: "Reliability", sections: [{ title: "The problem", body: "Dangler connections positioned inside the assembly were difficult to access, while barrel rotation created opportunities for rubbing and wear. This made routine connection work harder and contributed to repeated dangler maintenance." }, { title: "Design approach", body: "The improvement focused on relocating the connection access and managing the dangler routing so maintenance personnel could reach the connection more easily while reducing interference with the rotating assembly." }, { title: "Manufacturing & serviceability", body: "The design was considered from the perspective of practical installation, access, routing, and repeatable maintenance. The goal was not simply to move the connection, but to make the interface easier to work on and less exposed to the recurring wear mechanism." }, { title: "Result", body: "The resulting arrangement improves accessibility and addresses the recurring wear mechanism associated with rotation, supporting more reliable dangler operation and easier maintenance." }], highlights: ["Accessibility", "Dangler routing", "Reliability", "Maintenance"] },
  { title: "Agricultural Utility Vehicle", category: "Product Design", tags: ["Vehicle Design", "Fabrication", "Mechanism", "Agriculture", "Prototype Testing"], description: "Developed and tested a multipurpose Agricultural Utility Vehicle by adapting a compact vehicle platform for grass cutting, cultivation, and row making, progressing through fabrication, painting, prototype testing, failure analysis, and redesign.", metric: "Research Project", hero: "/projects/auv/FInal%201.jpg", gallery: [
    { src: "/projects/auv/Scrap%201.JPG", caption: "Scrap vehicle selection — donor platform used to begin development." },
    { src: "/projects/auv/Scrap%202.JPG", caption: "Scrap vehicle selection — donor platform and initial assessment." },
    { src: "/projects/auv/Prototype%201.png", caption: "First prototype — initial integrated vehicle and agricultural mechanisms." },
    { src: "/projects/auv/Cultivator.JPG", caption: "Mechanical fabrication — cultivator mechanism development." },
    { src: "/projects/auv/Cutter.jpg", caption: "Mechanical fabrication — cutter mechanism development." },
    { src: "/projects/auv/Paint.JPG", caption: "Painted prototype — vehicle after fabrication and finishing." },
    { src: "/projects/auv/Prototype%202.jpg", caption: "Second prototype — painted vehicle with integrated systems." },
    { src: "/projects/auv/Failure.JPG", caption: "Prototype failure — cultivator failure identified during testing." },
    { src: "/projects/auv/Remanufacture.jpg", caption: "Redesign and remanufacture — corrected cultivator development." },
    { src: "/projects/auv/AUV%20Model.png", caption: "Redesign — Agricultural Utility Vehicle model and mechanism layout." },
    { src: "/projects/auv/FInal%201.jpg", caption: "Complete AUV — final vehicle demonstrated in the field." },
    { src: "/projects/auv/Updated.jpg", caption: "Complete AUV — final vehicle and project team." }
  ], sections: [{ title: "Project objective", body: "The research project focused on developing a multipurpose Agricultural Utility Vehicle capable of carrying out several agricultural operations with a compact, practical platform." }, { title: "Fabrication & first prototype", body: "The development began with a scrap/donor vehicle platform. The agricultural mechanisms were manufactured and integrated, including the cultivator and cutter assemblies, followed by fabrication and assembly of the first working prototype." }, { title: "Paint & second prototype", body: "After the initial prototype build, the vehicle was painted and the design was developed into a second prototype with the agricultural mechanisms and vehicle systems integrated for further evaluation." }, { title: "Testing & failure analysis", body: "The second prototype was tested under operating conditions. Testing exposed a failure in the cultivator system, providing practical feedback on the mechanism and highlighting the need for a manufacturing and design correction rather than treating the first successful-looking build as final." }, { title: "Remanufacture & final prototype", body: "The cultivator was remanufactured based on the observed failure, then reassembled and tested again. The corrected cultivator completed the final testing successfully, resulting in a completed and functional prototype." }, { title: "Reported outcome", body: "The completed vehicle combines a compact platform with task-specific agricultural mechanisms for grass cutting, cultivation, and row making. The paper reports a 35–40% reduction in cost compared with conventional separate equipment." }], highlights: ["Scrap/donor vehicle platform", "Cultivator manufacturing", "Cutter manufacturing", "First prototype", "Second prototype", "Prototype testing", "Failure analysis", "Cultivator remanufacture", "Final successful testing", "35–40% reported cost reduction"] }
];

const skills = [["CAD & Product Design", "SolidWorks • AutoCAD • Mechanical assemblies • Design iteration"], ["Manufacturing", "DFM/DFA • Fabrication • Prototyping • 3D printing"], ["Problem Solving", "Root-cause analysis • 5 Whys • Fishbone • Six Sigma"], ["Engineering", "Mechanisms • Maintenance • Materials • Technical documentation"]];
const navItems = ["home", "projects", "experience", "education", "skills", "research", "resume", "contact"];
const categories = ["All", "Design", "Maintenance", "Safety", "Mechanism", "Manufacturing", "Product Design"];

export default function PortfolioShell() {
  const [ashOpen, setAshOpen] = useState(false), [ashPrompt, setAshPrompt] = useState(""), [search, setSearch] = useState(""), [category, setCategory] = useState("All"), [commandOpen, setCommandOpen] = useState(false), [selectedProject, setSelectedProject] = useState<Project | null>(null), [labProject, setLabProject] = useState<Project>(projects[0]), [recruiterOpen, setRecruiterOpen] = useState(false), [recruiterRole, setRecruiterRole] = useState("Mechanical Design");
  useEffect(() => { const key=(e:KeyboardEvent)=>{ if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setCommandOpen(v=>!v);} if(e.key==="Escape"){setCommandOpen(false);setAshOpen(false);setSelectedProject(null);setRecruiterOpen(false);} }; window.addEventListener("keydown",key); return()=>window.removeEventListener("keydown",key); },[]);
  useEffect(() => { fetch("/api/visitor", {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({page:window.location.pathname,event_type:"page_view",device:/Mobi|Android/i.test(navigator.userAgent)?"mobile":"desktop",browser:navigator.userAgent,referrer:document.referrer})}).catch(()=>{}); },[]);
  const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return projects.filter(p=>(category==="All"||p.category===category)&&(!q||`${p.title} ${p.category} ${p.tags.join(" ")} ${p.description}`.toLowerCase().includes(q)));},[search,category]);
  const openAshForProject=(p:Project)=>{setAshPrompt(`Tell me about the "${p.title}" project in Ashish's portfolio. Explain the problem, what was changed, and the engineering value in a concise recruiter-friendly way.`);setSelectedProject(null);setAshOpen(true);};
  const recruiterDescriptions:Record<string,string>={"Mechanical Design":"Industrial mechanical design, assemblies, mechanisms, CAD iteration, and practical serviceability.",Manufacturing:"DFM thinking, fabrication, prototyping, process improvement, and practical shop-floor constraints.","Product Development":"Problem definition, mechanism development, prototyping, fit checks, and design refinement.","Maintenance Engineering":"Serviceability, reliability, root-cause thinking, maintenance access, and downtime reduction.","CAD / SolidWorks":"SolidWorks-driven mechanical assemblies, design iteration, prototyping, and engineering documentation."};
  const recruiterRoles=Object.keys(recruiterDescriptions), recruiterSummary=recruiterDescriptions[recruiterRole];
  const recruiterProjects=useMemo(()=>{const terms=( {"Mechanical Design":["design","cad","mechanism","solidworks"],Manufacturing:["manufacturing","dfm","fabrication","prototyping"],"Product Development":["product","mechanism","design","prototyping"],"Maintenance Engineering":["maintenance","serviceability","reliability","root cause"],"CAD / SolidWorks":["cad","solidworks","design"]} as Record<string,string[]>)[recruiterRole]||[];return projects.map(p=>({p,s:terms.reduce((n,t)=>n+(`${p.title} ${p.category} ${p.tags.join(" ")} ${p.description} ${p.highlights?.join(" ")||""}`.toLowerCase().includes(t)?1:0),0)})).sort((a,b)=>b.s-a.s).slice(0,3).map(x=>x.p);},[recruiterRole]);
  const scrollTo=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setCommandOpen(false);};
  return <main>
    <header className="nav"><button className="brand" onClick={()=>scrollTo("home")}><span className="brand-mark">AK</span><span><strong>ASHISH KUDU</strong><small>MECHANICAL ENGINEER</small></span></button><nav>{navItems.map(i=><button key={i} onClick={()=>scrollTo(i)}>{i}</button>)}</nav><div className="nav-actions"><button className="recruiter-trigger" onClick={()=>setRecruiterOpen(true)}>⚡ Recruiter Mode</button><button className="search-trigger" onClick={()=>setCommandOpen(true)}>⌕ <kbd>⌘ K</kbd></button></div></header>
    <section id="home" className="hero"><div className="blueprint-grid"/><div className="hero-copy"><div className="availability"><i/> AVAILABLE FOR OPPORTUNITIES</div><p className="kicker">MECHANICAL DESIGN • MANUFACTURING • PRODUCT DEVELOPMENT</p><h1>Designing solutions.<br/><span>Building impact.</span></h1><p className="hero-lede">Mechanical engineer specializing in design and manufacturing, with hands-on experience turning industrial challenges into practical, manufacturable solutions.</p><div className="stats"><div><b>7+</b><span>Engineering Projects</span></div><div><b>4</b><span>Industry Experiences</span></div><div><b>1</b><span>Research Publication</span></div><div><b>MS</b><span>Clemson University</span></div></div><div className="actions"><button className="primary" onClick={()=>scrollTo("projects")}>View Projects →</button><button className="secondary" onClick={()=>scrollTo("resume")}>View Resume ↗</button></div></div><div className="avatar-stage"><CursorNetwork/><MechanicalElements/><img className="hero-portrait" src="/ashish-cutout.png" alt="Ashish Kudu" draggable={false}/></div><div className="hero-assistant-card"><div className="assistant-top"><div><b>ASH</b><span>Engineering Assistant</span></div><i/></div><p>Ask me about Ashish&apos;s projects, skills, experience, or research.</p><button onClick={()=>setAshOpen(true)}>Open ASH →</button></div></section>
    <section id="projects" className="section"><div className="section-head"><div><p className="kicker">ENGINEERING WORK</p><h2>Featured projects</h2></div><div className="filters">{categories.map(i=><button key={i} className={category===i?"active":""} onClick={()=>setCategory(i)}>{i}</button>)}</div></div><div className="project-grid">{filtered.map(p=><article className="project-card" key={p.title} tabIndex={0} role="button" onClick={()=>setSelectedProject(p)}><div className="project-visual">{p.hero?<img src={p.hero} alt=""/>:<div className="cad-lines"/>}<span>{p.metric}</span></div><div className="project-body"><small>{p.category.toUpperCase()}</small><h3>{p.title}</h3><p>{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><button onClick={e=>{e.stopPropagation();openAshForProject(p)}}>Ask ASH about this →</button></div></article>)}</div></section>
    <section id="lab" className="section engineering-lab"><div className="section-head lab-head"><div><p className="kicker">INTERACTIVE ENGINEERING LAB</p><h2>Explore how I solve problems.</h2><p className="lab-lede">Pick a project and move through the engineering story: problem, approach, result, and the thinking behind the design.</p></div><div className="lab-selector" role="tablist">{projects.map(p=><button key={p.title} className={labProject.title===p.title?"active":""} onClick={()=>setLabProject(p)}>{p.title}</button>)}</div></div><div className="lab-shell"><div className="lab-visual">{labProject.hero?<img src={labProject.hero} alt=""/>:<div className="lab-placeholder"><span>ENGINEERING SYSTEM</span><strong>{labProject.title}</strong><i/></div>}<div className="lab-overlay-label"><span>{labProject.category.toUpperCase()}</span><b>{labProject.metric}</b></div></div><div className="lab-story"><div className="lab-story-top"><div><span className="project-modal-label">CURRENT EXPLORATION</span><h3>{labProject.title}</h3></div><button className="secondary lab-case-button" onClick={()=>setSelectedProject(labProject)}>Open full case study →</button></div><div className="lab-steps">{(labProject.sections||[]).slice(0,3).map((s,i)=><button key={s.title} className="lab-step" onClick={()=>setSelectedProject(labProject)}><span>0{i+1}</span><div><b>{s.title}</b><p>{s.body}</p></div><em>↗</em></button>)}</div>{labProject.highlights&&<div className="lab-focus"><span>ENGINEERING FOCUS</span><div>{labProject.highlights.slice(0,5).map(x=><b key={x}>{x}</b>)}</div></div>}</div></div></section>
    <section id="experience" className="section split"><div><p className="kicker">PROFESSIONAL EXPERIENCE</p><h2>Engineering in the real world.</h2><p className="lab-lede">Hands-on experience across industrial engineering, mechanical design, vehicle maintenance, railway engineering, manufacturing, testing, and technical documentation.</p></div><div className="timeline">
      <div><span>01</span><div><h3>Engineering Intern — Co-op</h3><strong>Aalberts Surface Technologies · Piedmont, SC</strong><small>Fall 2026 – Present</small><p>Current engineering co-op focused on hands-on engineering work in an industrial manufacturing environment.</p></div></div>
      <div><span>02</span><div><h3>Mechanical Jr. Design Engineer</h3><strong>Synergy Water Park Rides Pvt. Ltd. · Mumbai, India</strong><small>Jan 2025 – June 2025</small><p>• Designed and developed 15+ mechanical components and assemblies using SolidWorks and AutoCAD, improving design turnaround time by 20% while ensuring manufacturability and reducing production cost.</p><p>• Collaborated with a team of 6 engineers to implement lean layout changes, reducing assembly time by 15% and improving material flow efficiency.</p><p>• Conducted performance analysis on 10+ design iterations, improving component durability by 15% through design optimization.</p><p>• Participated in cross-functional design reviews with 5+ stakeholders, ensuring 100% compliance with manufacturing and quality standards.</p></div></div>
      <div><span>03</span><div><h3>Diagnostic &amp; Maintenance Intern</h3><strong>Ashok Leyland · Mumbai, India</strong><small>Aug 2021 – Dec 2021</small><p>• Assisted in diagnosing 25+ mechanical failures in commercial vehicles, improving troubleshooting efficiency by 20%.</p><p>• Performed maintenance on 50+ heavy vehicles (HMV, MCV, HCV), ensuring operational reliability and reduced downtime.</p><p>• Utilized OEM diagnostic tools and service manuals to improve repair accuracy and maintenance efficiency.</p><p>• Applied preventive maintenance schedules to reduce breakdowns by 15% and improve vehicle reliability.</p><p>• Coordinated with 5+ technicians to ensure proper torque, alignment, and assembly practices, improving service quality.</p></div></div>
      <div><span>04</span><div><h3>Engineering Intern</h3><strong>Indian Railway · Mumbai, India</strong><small>Dec 2022 – Jan 2023</small><p>• Supported reliability assessment of 20+ mechanical systems, improving maintenance documentation accuracy.</p><p>• Assisted in system inspections and technical reporting, contributing to a 10% improvement in operational efficiency.</p><p>• Gained hands-on experience in mechanical systems maintenance, documentation, and safety compliance.</p></div></div>
    </div></section>
    <section id="education" className="section split"><div><p className="kicker">EDUCATION</p><h2>Mechanical engineering foundation.</h2><p className="lab-lede">Academic training focused on mechanical engineering with a strong emphasis on design, manufacturing, CAD, analysis, and product development.</p></div><div className="timeline">
      <div><span>01</span><div><h3>Master of Science in Mechanical Engineering</h3><strong>Clemson University · Clemson, SC</strong><small>Aug. 2025 – May 2027</small><p>Graduate study in Mechanical Engineering with a design and manufacturing focus.</p></div></div>
      <div><span>02</span><div><h3>Bachelor of Engineering in Mechanical Engineering</h3><strong>University of Mumbai · Mumbai, India</strong><small>Aug. 2018 – May 2021</small><p>Undergraduate mechanical engineering education forming the foundation for CAD, manufacturing, mechanical systems, and product development work.</p></div></div>
    </div></section>
    <section id="skills" className="section"><p className="kicker">CAPABILITY STACK</p><h2>Tools I use to solve problems.</h2><div className="skill-grid">{skills.map(([t,x])=><div className="skill-card" key={t}><span>✦</span><h3>{t}</h3><p>{x}</p></div>)}</div><div className="skill-grid"><div className="skill-card"><span>✦</span><h3>Design &amp; Analysis</h3><p>GD&amp;T • DFM/DFA • Tolerance Stack-Up • FEA • Design Optimization</p></div><div className="skill-card"><span>✦</span><h3>CAD Tools</h3><p>SolidWorks (Certified) • AutoCAD (Certified) • Inventor</p></div><div className="skill-card"><span>✦</span><h3>Computational &amp; Tools</h3><p>MATLAB • Minitab • Excel</p></div><div className="skill-card"><span>✦</span><h3>Manufacturing &amp; Testing</h3><p>Prototyping • Material Selection • Performance Evaluation • Field Testing</p></div></div></section>
    <section id="research" className="section research"><div><p className="kicker">RESEARCH</p><h2>Engineering beyond the project floor.</h2><p>Research and academic work presented with the same emphasis on clear problem definition, method, evidence, and technical communication.</p></div><div className="research-card"><span>PUBLICATION</span><h3>Research portfolio</h3><p>Publication details, abstract, methodology, contribution, and downloadable paper can live here.</p><button>View research →</button></div></section>
    <section id="resume" className="section resume"><div><p className="kicker">RESUME</p><h2>Mechanical engineering, design &amp; manufacturing.</h2><p>View the current resume for education, experience, projects, skills, and research.</p></div><a className="primary" href="/resume.pdf" target="_blank">Open Resume ↗</a></section>
    <section id="contact" className="section contact"><p className="kicker">CONTACT</p><h2>Let&apos;s build something useful.</h2><p>Open to mechanical design, manufacturing, product development, and related engineering opportunities.</p></section>
    {selectedProject&&<div className="modal-backdrop" onClick={()=>setSelectedProject(null)}><div className="project-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelectedProject(null)}>×</button><p className="project-modal-label">{selectedProject.category.toUpperCase()}</p><h2>{selectedProject.title}</h2><p className="project-modal-description">{selectedProject.description}</p>{selectedProject.gallery&&<div className="project-gallery">{selectedProject.gallery.map((g,i)=><figure key={g.src}><img src={g.src} alt={g.caption}/><figcaption><span>{String(i+1).padStart(2,"0")}</span>{g.caption}</figcaption></figure>)}</div>}<div className="project-modal-sections">{(selectedProject.sections||[]).map(s=><section key={s.title}><h3>{s.title}</h3><p>{s.body}</p></section>)}</div>{selectedProject.highlights&&<div className="modal-highlights">{selectedProject.highlights.map(h=><span key={h}>{h}</span>)}</div>}</div></div>}
    {commandOpen&&<div className="command-backdrop" onClick={()=>setCommandOpen(false)}><div className="command" onClick={e=>e.stopPropagation()}><input autoFocus placeholder="Search projects, skills, experience..." value={search} onChange={e=>setSearch(e.target.value)}/><div>{projects.filter(p=>`${p.title} ${p.description}`.toLowerCase().includes(search.toLowerCase())).map(p=><button key={p.title} onClick={()=>{setSelectedProject(p);setCommandOpen(false)}}>{p.title}<span>{p.category}</span></button>)}</div></div></div>}
    {recruiterOpen&&<div className="command-backdrop" onClick={()=>setRecruiterOpen(false)}><div className="recruiter-panel" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setRecruiterOpen(false)}>×</button><p className="kicker">RECRUITER MODE</p><h2>Find the strongest fit.</h2><div className="recruiter-roles">{recruiterRoles.map(r=><button className={r===recruiterRole?"active":""} key={r} onClick={()=>setRecruiterRole(r)}>{r}</button>)}</div><p>{recruiterSummary}</p><div className="recruiter-projects">{recruiterProjects.map(p=><button key={p.title} onClick={()=>{setSelectedProject(p);setRecruiterOpen(false)}}><b>{p.title}</b><span>{p.category}</span></button>)}</div></div></div>}
    <ASHAssistant open={ashOpen} onClose={()=>setAshOpen(false)} initialPrompt={ashPrompt}/>
  </main>;
}
